export const SCHEMA_VERSION:string;
export const CALENDAR_LIMITS:{jsonBytes:number;fileBytes:number;listPage:number;maxOffset:number;mime:string;remainingQuota:null};
export type PlatformField={key:string;label:string;options:string[]|null;required:boolean};
export const PLATFORMS:Record<string,{id:string;label:string;docs:string;fields:PlatformField[];platformCapabilities:Record<string,unknown>;adapter:Record<string,any>;media:Record<string,unknown>}>;
export function platformSchema(id:string):any;
export function settingsToForm(settings:any):Record<string,any>;
export function formToSettings(platform:string,form:Record<string,any>):any;
export function mergeSettings(base:any,supplied:any):any;
export function settingsIssues(settings:any,options?:{legacy?:boolean}):string[];
